@startuml
'https://plantuml.com/activity-diagram-beta

start

:Jenkins;
note right: Invoke top-level Maven targets clean test -P Smoke_Test

:pom.xml(profiles);
note right: <id>Smoke_Test</id>

:CucumberSmokeTest.xml;
note right: <class name="Runners.Smoke_Test_Runner"> </class>

:Smoke_Test_Runner;
note right: tags = "@Smoketest"

:FeatureFiles, Generiek_FeatureFiles;

stop

@enduml
