@startuml
'https://plantuml.com/activity-diagram-beta

start


:Jenkins;
->//Invoke top-level Maven targets =>//
     //clean test -P Smoke_Test//;

:pom.xml(profiles);
->//  <id>Smoke_Test</id> //;

:CucumberSmokeTest.xml;
->// <class name="Runners.Smoke_Test_Runner"> </class>//;

:Smoke_Test_Runner;
->//tags = "@Smoketest"//;

:FeatureFiles, Generiek_FeatureFiles;


stop

@enduml
